//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_weblinks
    {
        public long id { get; set; }
        public int catid { get; set; }
        public int sid { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
        public int hits { get; set; }
        public bool state { get; set; }
        public int checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public int ordering { get; set; }
        public bool archived { get; set; }
        public bool approved { get; set; }
        public int access { get; set; }
        public string @params { get; set; }
        public string language { get; set; }
        public System.DateTime created { get; set; }
        public long created_by { get; set; }
        public string created_by_alias { get; set; }
        public System.DateTime modified { get; set; }
        public long modified_by { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public string metadata { get; set; }
        public byte featured { get; set; }
        public string xreference { get; set; }
        public System.DateTime publish_up { get; set; }
        public System.DateTime publish_down { get; set; }
    }
}
