//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_user_read
    {
        public int user_id { get; set; }
        public int topic_id { get; set; }
        public int category_id { get; set; }
        public int message_id { get; set; }
        public int time { get; set; }
    }
}
