//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_languages
    {
        public long lang_id { get; set; }
        public string lang_code { get; set; }
        public string title { get; set; }
        public string title_native { get; set; }
        public string sef { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public string sitename { get; set; }
        public int published { get; set; }
        public long access { get; set; }
        public int ordering { get; set; }
    }
}
