//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_keywords
    {
        public int id { get; set; }
        public string name { get; set; }
        public int public_count { get; set; }
        public int total_count { get; set; }
    }
}
