//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_mail
    {
        public int mailid { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string altbody { get; set; }
        public Nullable<sbyte> published { get; set; }
        public Nullable<long> senddate { get; set; }
        public Nullable<long> created { get; set; }
        public string fromname { get; set; }
        public string fromemail { get; set; }
        public string replyname { get; set; }
        public string replyemail { get; set; }
        public string type { get; set; }
        public sbyte visible { get; set; }
        public Nullable<long> userid { get; set; }
        public string alias { get; set; }
        public string attach { get; set; }
        public sbyte html { get; set; }
        public short tempid { get; set; }
        public string key { get; set; }
        public string frequency { get; set; }
        public string @params { get; set; }
        public Nullable<long> sentby { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public string filter { get; set; }
    }
}
