//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_xmap_sitemap
    {
        public int id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string introtext { get; set; }
        public string metadesc { get; set; }
        public string metakey { get; set; }
        public string attribs { get; set; }
        public string selections { get; set; }
        public string excluded_items { get; set; }
        public Nullable<int> is_default { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> access { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<int> count_xml { get; set; }
        public Nullable<int> count_html { get; set; }
        public Nullable<int> views_xml { get; set; }
        public Nullable<int> views_html { get; set; }
        public Nullable<int> lastvisit_xml { get; set; }
        public Nullable<int> lastvisit_html { get; set; }
    }
}
