//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_userstats
    {
        public int mailid { get; set; }
        public long subid { get; set; }
        public byte html { get; set; }
        public byte sent { get; set; }
        public long senddate { get; set; }
        public byte open { get; set; }
        public int opendate { get; set; }
        public sbyte bounce { get; set; }
        public sbyte fail { get; set; }
        public string ip { get; set; }
    }
}
