//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_polls_users
    {
        public Nullable<int> pollid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> votes { get; set; }
        public System.DateTime lasttime { get; set; }
        public Nullable<int> lastvote { get; set; }
    }
}
