//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_jcomments_version
    {
        public string version { get; set; }
        public string previous { get; set; }
        public System.DateTime installed { get; set; }
        public System.DateTime updated { get; set; }
    }
}
