//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_user_topics
    {
        public int user_id { get; set; }
        public int topic_id { get; set; }
        public int category_id { get; set; }
        public int posts { get; set; }
        public int last_post_id { get; set; }
        public sbyte owner { get; set; }
        public sbyte favorite { get; set; }
        public sbyte subscribed { get; set; }
        public string @params { get; set; }
    }
}
