//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_subscriber_copy
    {
        public long subid { get; set; }
        public string email { get; set; }
        public long userid { get; set; }
        public string name { get; set; }
        public Nullable<long> created { get; set; }
        public sbyte confirmed { get; set; }
        public sbyte enabled { get; set; }
        public sbyte accept { get; set; }
        public string ip { get; set; }
        public sbyte html { get; set; }
        public string key { get; set; }
        public long confirmed_date { get; set; }
        public string confirmed_ip { get; set; }
        public long lastopen_date { get; set; }
        public long lastclick_date { get; set; }
    }
}
