//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_users
    {
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string usertype { get; set; }
        public sbyte block { get; set; }
        public Nullable<sbyte> sendEmail { get; set; }
        public System.DateTime registerDate { get; set; }
        public System.DateTime lastvisitDate { get; set; }
        public string activation { get; set; }
        public string @params { get; set; }
        public string port { get; set; }
    }
}
