//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_banner_clients
    {
        public int id { get; set; }
        public string name { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public string extrainfo { get; set; }
        public sbyte state { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public string metakey { get; set; }
        public sbyte own_prefix { get; set; }
        public string metakey_prefix { get; set; }
        public sbyte purchase_type { get; set; }
        public sbyte track_clicks { get; set; }
        public sbyte track_impressions { get; set; }
    }
}
