//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_jcomments_subscriptions
    {
        public long id { get; set; }
        public long object_id { get; set; }
        public string object_group { get; set; }
        public string lang { get; set; }
        public long userid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string hash { get; set; }
        public bool published { get; set; }
        public string source { get; set; }
    }
}
