//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_jcomments_custom_bbcodes
    {
        public long id { get; set; }
        public string name { get; set; }
        public string simple_pattern { get; set; }
        public string simple_replacement_html { get; set; }
        public string simple_replacement_text { get; set; }
        public string pattern { get; set; }
        public string replacement_html { get; set; }
        public string replacement_text { get; set; }
        public string button_acl { get; set; }
        public string button_open_tag { get; set; }
        public string button_close_tag { get; set; }
        public string button_title { get; set; }
        public string button_prompt { get; set; }
        public string button_image { get; set; }
        public string button_css { get; set; }
        public bool button_enabled { get; set; }
        public long ordering { get; set; }
        public bool published { get; set; }
    }
}
