//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_contact_details
    {
        public int id { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string con_position { get; set; }
        public string address { get; set; }
        public string suburb { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string postcode { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string misc { get; set; }
        public string image { get; set; }
        public string imagepos { get; set; }
        public string email_to { get; set; }
        public bool default_con { get; set; }
        public bool published { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public int ordering { get; set; }
        public string @params { get; set; }
        public int user_id { get; set; }
        public int catid { get; set; }
        public long access { get; set; }
        public string mobile { get; set; }
        public string webpage { get; set; }
        public string sortname1 { get; set; }
        public string sortname2 { get; set; }
        public string sortname3 { get; set; }
        public string language { get; set; }
        public System.DateTime created { get; set; }
        public long created_by { get; set; }
        public string created_by_alias { get; set; }
        public System.DateTime modified { get; set; }
        public long modified_by { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public string metadata { get; set; }
        public byte featured { get; set; }
        public string xreference { get; set; }
        public System.DateTime publish_up { get; set; }
        public System.DateTime publish_down { get; set; }
    }
}
