//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_extensions
    {
        public int extension_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string element { get; set; }
        public string folder { get; set; }
        public sbyte client_id { get; set; }
        public sbyte enabled { get; set; }
        public long access { get; set; }
        public sbyte @protected { get; set; }
        public string manifest_cache { get; set; }
        public string @params { get; set; }
        public string custom_data { get; set; }
        public string system_data { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public Nullable<int> ordering { get; set; }
        public Nullable<int> state { get; set; }
    }
}
