//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_attachments
    {
        public int id { get; set; }
        public int mesid { get; set; }
        public int userid { get; set; }
        public string hash { get; set; }
        public Nullable<int> size { get; set; }
        public string folder { get; set; }
        public string filetype { get; set; }
        public string filename { get; set; }
    }
}
