//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_modules
    {
        public int id { get; set; }
        public string title { get; set; }
        public string note { get; set; }
        public string content { get; set; }
        public int ordering { get; set; }
        public string position { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public System.DateTime publish_up { get; set; }
        public System.DateTime publish_down { get; set; }
        public bool published { get; set; }
        public string module { get; set; }
        public long access { get; set; }
        public byte showtitle { get; set; }
        public string @params { get; set; }
        public sbyte client_id { get; set; }
        public string language { get; set; }
    }
}
