//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_phocagallery_categories
    {
        public int id { get; set; }
        public int parent_id { get; set; }
        public int owner_id { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string image { get; set; }
        public string section { get; set; }
        public string image_position { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
        public bool published { get; set; }
        public bool approved { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public string editor { get; set; }
        public int ordering { get; set; }
        public byte access { get; set; }
        public int count { get; set; }
        public int hits { get; set; }
        public string accessuserid { get; set; }
        public string uploaduserid { get; set; }
        public string deleteuserid { get; set; }
        public string userfolder { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public int zoom { get; set; }
        public string geotitle { get; set; }
        public string extid { get; set; }
        public string exta { get; set; }
        public string extu { get; set; }
        public string extauth { get; set; }
        public int extfbuid { get; set; }
        public string extfbcatid { get; set; }
        public string @params { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public string metadata { get; set; }
        public string language { get; set; }
    }
}
