//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_queue
    {
        public long senddate { get; set; }
        public long subid { get; set; }
        public int mailid { get; set; }
        public Nullable<byte> priority { get; set; }
        public byte @try { get; set; }
        public string paramqueue { get; set; }
    }
}
