//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_wf_profiles
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string users { get; set; }
        public string types { get; set; }
        public string components { get; set; }
        public sbyte area { get; set; }
        public string device { get; set; }
        public string rows { get; set; }
        public string plugins { get; set; }
        public sbyte published { get; set; }
        public int ordering { get; set; }
        public sbyte checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public string @params { get; set; }
    }
}
