//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_phocagallery
    {
        public long id { get; set; }
        public int catid { get; set; }
        public int sid { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string filename { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
        public int hits { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public int zoom { get; set; }
        public string geotitle { get; set; }
        public int userid { get; set; }
        public string videocode { get; set; }
        public int vmproductid { get; set; }
        public int imgorigsize { get; set; }
        public bool published { get; set; }
        public bool approved { get; set; }
        public int checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public int ordering { get; set; }
        public string @params { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public string metadata { get; set; }
        public string extlink1 { get; set; }
        public string extlink2 { get; set; }
        public string extid { get; set; }
        public bool exttype { get; set; }
        public string extl { get; set; }
        public string extm { get; set; }
        public string exts { get; set; }
        public string exto { get; set; }
        public string extw { get; set; }
        public string exth { get; set; }
        public string language { get; set; }
    }
}
