//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_jcomments_reports
    {
        public long id { get; set; }
        public long commentid { get; set; }
        public long userid { get; set; }
        public string name { get; set; }
        public string ip { get; set; }
        public System.DateTime date { get; set; }
        public string reason { get; set; }
        public bool status { get; set; }
    }
}
