//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_template
    {
        public int tempid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string body { get; set; }
        public string altbody { get; set; }
        public Nullable<long> created { get; set; }
        public sbyte published { get; set; }
        public sbyte premium { get; set; }
        public Nullable<int> ordering { get; set; }
        public string namekey { get; set; }
        public string styles { get; set; }
        public string subject { get; set; }
        public string stylesheet { get; set; }
        public string fromname { get; set; }
        public string fromemail { get; set; }
        public string replyname { get; set; }
        public string replyemail { get; set; }
        public string thumb { get; set; }
        public string readmore { get; set; }
    }
}
