//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_topics
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public string subject { get; set; }
        public int icon_id { get; set; }
        public sbyte locked { get; set; }
        public sbyte hold { get; set; }
        public int ordering { get; set; }
        public int posts { get; set; }
        public int hits { get; set; }
        public int attachments { get; set; }
        public int poll_id { get; set; }
        public int moved_id { get; set; }
        public int first_post_id { get; set; }
        public int first_post_time { get; set; }
        public int first_post_userid { get; set; }
        public string first_post_message { get; set; }
        public string first_post_guest_name { get; set; }
        public int last_post_id { get; set; }
        public int last_post_time { get; set; }
        public int last_post_userid { get; set; }
        public string last_post_message { get; set; }
        public string last_post_guest_name { get; set; }
        public string @params { get; set; }
    }
}
