//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_phocagallery_fb_users
    {
        public int id { get; set; }
        public string appid { get; set; }
        public string appsid { get; set; }
        public string uid { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public string secret { get; set; }
        public string base_domain { get; set; }
        public string expires { get; set; }
        public string session_key { get; set; }
        public string access_token { get; set; }
        public string sig { get; set; }
        public string fanpageid { get; set; }
        public bool published { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public int ordering { get; set; }
        public string comments { get; set; }
        public string @params { get; set; }
        public string language { get; set; }
    }
}
