//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_updates
    {
        public int update_id { get; set; }
        public Nullable<int> update_site_id { get; set; }
        public Nullable<int> extension_id { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string element { get; set; }
        public string type { get; set; }
        public string folder { get; set; }
        public Nullable<sbyte> client_id { get; set; }
        public string version { get; set; }
        public string data { get; set; }
        public string detailsurl { get; set; }
        public string infourl { get; set; }
    }
}
