//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_finder_tokens_aggregate
    {
        public long term_id { get; set; }
        public string map_suffix { get; set; }
        public string term { get; set; }
        public string stem { get; set; }
        public bool common { get; set; }
        public bool phrase { get; set; }
        public bool context { get; set; }
    }
}
