//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_user_categories
    {
        public int user_id { get; set; }
        public int category_id { get; set; }
        public sbyte role { get; set; }
        public Nullable<System.DateTime> allreadtime { get; set; }
        public sbyte subscribed { get; set; }
        public string @params { get; set; }
    }
}
