//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_stats
    {
        public int mailid { get; set; }
        public long senthtml { get; set; }
        public long senttext { get; set; }
        public long senddate { get; set; }
        public int openunique { get; set; }
        public long opentotal { get; set; }
        public int bounceunique { get; set; }
        public int fail { get; set; }
        public long clicktotal { get; set; }
        public int clickunique { get; set; }
        public int unsub { get; set; }
        public int forward { get; set; }
        public string bouncedetails { get; set; }
    }
}
