//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_filter
    {
        public int filid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<byte> published { get; set; }
        public Nullable<long> lasttime { get; set; }
        public string trigger { get; set; }
        public string report { get; set; }
        public string action { get; set; }
        public string filter { get; set; }
    }
}
