//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_list
    {
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> ordering { get; set; }
        public int listid { get; set; }
        public Nullable<sbyte> published { get; set; }
        public Nullable<long> userid { get; set; }
        public string alias { get; set; }
        public string color { get; set; }
        public sbyte visible { get; set; }
        public Nullable<int> welmailid { get; set; }
        public Nullable<int> unsubmailid { get; set; }
        public string type { get; set; }
        public string access_sub { get; set; }
        public string access_manage { get; set; }
        public string languages { get; set; }
    }
}
