//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_template_styles
    {
        public long id { get; set; }
        public string template { get; set; }
        public bool client_id { get; set; }
        public string home { get; set; }
        public string title { get; set; }
        public string @params { get; set; }
    }
}
