//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_rules
    {
        public int ruleid { get; set; }
        public string name { get; set; }
        public Nullable<short> ordering { get; set; }
        public string regex { get; set; }
        public string executed_on { get; set; }
        public string action_message { get; set; }
        public string action_user { get; set; }
        public byte published { get; set; }
    }
}
