//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_session
    {
        public string session_id { get; set; }
        public byte client_id { get; set; }
        public Nullable<byte> guest { get; set; }
        public string time { get; set; }
        public string data { get; set; }
        public Nullable<int> userid { get; set; }
        public string username { get; set; }
        public string usertype { get; set; }
    }
}
