//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_banners
    {
        public int id { get; set; }
        public int cid { get; set; }
        public int type { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public int imptotal { get; set; }
        public int impmade { get; set; }
        public int clicks { get; set; }
        public string clickurl { get; set; }
        public sbyte state { get; set; }
        public long catid { get; set; }
        public string description { get; set; }
        public string custombannercode { get; set; }
        public bool sticky { get; set; }
        public int ordering { get; set; }
        public string metakey { get; set; }
        public string @params { get; set; }
        public bool own_prefix { get; set; }
        public string metakey_prefix { get; set; }
        public sbyte purchase_type { get; set; }
        public sbyte track_clicks { get; set; }
        public sbyte track_impressions { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public System.DateTime publish_up { get; set; }
        public System.DateTime publish_down { get; set; }
        public System.DateTime reset { get; set; }
        public System.DateTime created { get; set; }
        public string language { get; set; }
    }
}
