//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_ranks
    {
        public int rank_id { get; set; }
        public string rank_title { get; set; }
        public int rank_min { get; set; }
        public bool rank_special { get; set; }
        public string rank_image { get; set; }
    }
}
