//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_thankyou
    {
        public int postid { get; set; }
        public int userid { get; set; }
        public int targetuserid { get; set; }
        public System.DateTime time { get; set; }
    }
}
