//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_finder_filters
    {
        public long filter_id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public bool state { get; set; }
        public System.DateTime created { get; set; }
        public long created_by { get; set; }
        public string created_by_alias { get; set; }
        public System.DateTime modified { get; set; }
        public long modified_by { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public long map_count { get; set; }
        public string data { get; set; }
        public string @params { get; set; }
    }
}
