//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_finder_links
    {
        public long link_id { get; set; }
        public string url { get; set; }
        public string route { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime indexdate { get; set; }
        public string md5sum { get; set; }
        public bool published { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> access { get; set; }
        public string language { get; set; }
        public System.DateTime publish_start_date { get; set; }
        public System.DateTime publish_end_date { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int type_id { get; set; }
        public byte[] @object { get; set; }
    }
}
