//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_jcomments_objects
    {
        public long id { get; set; }
        public long object_id { get; set; }
        public string object_group { get; set; }
        public string lang { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public byte access { get; set; }
        public long userid { get; set; }
        public byte expired { get; set; }
        public System.DateTime modified { get; set; }
    }
}
