//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_update_sites
    {
        public int update_site_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string location { get; set; }
        public Nullable<int> enabled { get; set; }
        public Nullable<long> last_check_timestamp { get; set; }
    }
}
