//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_jcomments_blacklist
    {
        public long id { get; set; }
        public string ip { get; set; }
        public long userid { get; set; }
        public System.DateTime created { get; set; }
        public long created_by { get; set; }
        public System.DateTime expire { get; set; }
        public string reason { get; set; }
        public string notes { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public string editor { get; set; }
    }
}
