//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_messages
    {
        public int id { get; set; }
        public Nullable<int> parent { get; set; }
        public Nullable<int> thread { get; set; }
        public int catid { get; set; }
        public string name { get; set; }
        public int userid { get; set; }
        public string email { get; set; }
        public string subject { get; set; }
        public int time { get; set; }
        public string ip { get; set; }
        public int topic_emoticon { get; set; }
        public sbyte locked { get; set; }
        public sbyte hold { get; set; }
        public Nullable<int> ordering { get; set; }
        public Nullable<int> hits { get; set; }
        public Nullable<sbyte> moved { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<int> modified_time { get; set; }
        public string modified_reason { get; set; }
    }
}
