//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_easybook
    {
        public int id { get; set; }
        public string gbip { get; set; }
        public string gbname { get; set; }
        public string gbmail { get; set; }
        public bool gbmailshow { get; set; }
        public string gbloca { get; set; }
        public string gbpage { get; set; }
        public Nullable<int> gbvote { get; set; }
        public string gbtext { get; set; }
        public Nullable<System.DateTime> gbdate { get; set; }
        public string gbtitle { get; set; }
        public string gbcomment { get; set; }
        public bool published { get; set; }
        public string gbicq { get; set; }
        public string gbaim { get; set; }
        public string gbmsn { get; set; }
        public string gbyah { get; set; }
        public string gbskype { get; set; }
    }
}
