//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_users_banned
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string ip { get; set; }
        public sbyte blocked { get; set; }
        public Nullable<System.DateTime> expiration { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_time { get; set; }
        public string reason_private { get; set; }
        public string reason_public { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_time { get; set; }
        public string comments { get; set; }
        public string @params { get; set; }
    }
}
