//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_categories
    {
        public int id { get; set; }
        public long asset_id { get; set; }
        public long parent_id { get; set; }
        public int lft { get; set; }
        public int rgt { get; set; }
        public long level { get; set; }
        public string path { get; set; }
        public string extension { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string note { get; set; }
        public string description { get; set; }
        public bool published { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public long access { get; set; }
        public string @params { get; set; }
        public string metadesc { get; set; }
        public string metakey { get; set; }
        public string metadata { get; set; }
        public long created_user_id { get; set; }
        public System.DateTime created_time { get; set; }
        public long modified_user_id { get; set; }
        public System.DateTime modified_time { get; set; }
        public long hits { get; set; }
        public string language { get; set; }
    }
}
