//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_usergroups
    {
        public long id { get; set; }
        public long parent_id { get; set; }
        public int lft { get; set; }
        public int rgt { get; set; }
        public string title { get; set; }
    }
}
