//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_jcomments
    {
        public long id { get; set; }
        public long parent { get; set; }
        public long thread_id { get; set; }
        public string path { get; set; }
        public bool level { get; set; }
        public long object_id { get; set; }
        public string object_group { get; set; }
        public string object_params { get; set; }
        public string lang { get; set; }
        public long userid { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string homepage { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        public string ip { get; set; }
        public System.DateTime date { get; set; }
        public short isgood { get; set; }
        public short ispoor { get; set; }
        public bool published { get; set; }
        public bool deleted { get; set; }
        public bool subscribe { get; set; }
        public string source { get; set; }
        public long source_id { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public string editor { get; set; }
    }
}
