//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_fields
    {
        public int fieldid { get; set; }
        public string fieldname { get; set; }
        public string namekey { get; set; }
        public string type { get; set; }
        public string value { get; set; }
        public byte published { get; set; }
        public Nullable<int> ordering { get; set; }
        public string options { get; set; }
        public byte core { get; set; }
        public byte required { get; set; }
        public byte backend { get; set; }
        public byte frontcomp { get; set; }
        public string @default { get; set; }
        public Nullable<byte> listing { get; set; }
    }
}
