//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_history
    {
        public long subid { get; set; }
        public long date { get; set; }
        public string ip { get; set; }
        public string action { get; set; }
        public string data { get; set; }
        public string source { get; set; }
        public Nullable<int> mailid { get; set; }
    }
}
