//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_redirect_links
    {
        public long id { get; set; }
        public string old_url { get; set; }
        public string new_url { get; set; }
        public string referer { get; set; }
        public string comment { get; set; }
        public sbyte published { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime modified_date { get; set; }
    }
}
