//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_content
    {
        public long id { get; set; }
        public long asset_id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string title_alias { get; set; }
        public string introtext { get; set; }
        public string fulltext { get; set; }
        public sbyte state { get; set; }
        public long sectionid { get; set; }
        public long mask { get; set; }
        public long catid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public long created_by { get; set; }
        public string created_by_alias { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public long modified_by { get; set; }
        public long checked_out { get; set; }
        public Nullable<System.DateTime> checked_out_time { get; set; }
        public Nullable<System.DateTime> publish_up { get; set; }
        public string images { get; set; }
        public Nullable<System.DateTime> publish_down { get; set; }
        public string urls { get; set; }
        public string attribs { get; set; }
        public long version { get; set; }
        public long parentid { get; set; }
        public int ordering { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public long access { get; set; }
        public long hits { get; set; }
        public string metadata { get; set; }
        public byte featured { get; set; }
        public string language { get; set; }
        public string xreference { get; set; }
    }
}
