//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_sessions
    {
        public int userid { get; set; }
        public string allowed { get; set; }
        public int lasttime { get; set; }
        public string readtopics { get; set; }
        public int currvisit { get; set; }
    }
}
