//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_newsfeeds
    {
        public int catid { get; set; }
        public long id { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string link { get; set; }
        public string filename { get; set; }
        public bool published { get; set; }
        public long numarticles { get; set; }
        public long cache_time { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public int ordering { get; set; }
        public sbyte rtl { get; set; }
        public long access { get; set; }
        public string language { get; set; }
        public string @params { get; set; }
        public System.DateTime created { get; set; }
        public long created_by { get; set; }
        public string created_by_alias { get; set; }
        public System.DateTime modified { get; set; }
        public long modified_by { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public string metadata { get; set; }
        public string xreference { get; set; }
        public System.DateTime publish_up { get; set; }
        public System.DateTime publish_down { get; set; }
    }
}
