//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_kunena_users
    {
        public int userid { get; set; }
        public string view { get; set; }
        public string signature { get; set; }
        public Nullable<int> moderator { get; set; }
        public Nullable<System.DateTime> banned { get; set; }
        public Nullable<int> ordering { get; set; }
        public Nullable<int> posts { get; set; }
        public string avatar { get; set; }
        public Nullable<int> karma { get; set; }
        public Nullable<int> karma_time { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> uhits { get; set; }
        public string personalText { get; set; }
        public sbyte gender { get; set; }
        public System.DateTime birthdate { get; set; }
        public string location { get; set; }
        public string icq { get; set; }
        public string aim { get; set; }
        public string yim { get; set; }
        public string msn { get; set; }
        public string skype { get; set; }
        public string twitter { get; set; }
        public string facebook { get; set; }
        public string gtalk { get; set; }
        public string myspace { get; set; }
        public string linkedin { get; set; }
        public string delicious { get; set; }
        public string friendfeed { get; set; }
        public string digg { get; set; }
        public string blogspot { get; set; }
        public string flickr { get; set; }
        public string bebo { get; set; }
        public string websitename { get; set; }
        public string websiteurl { get; set; }
        public sbyte rank { get; set; }
        public bool hideEmail { get; set; }
        public bool showOnline { get; set; }
        public Nullable<int> thankyou { get; set; }
    }
}
