//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_menu
    {
        public int id { get; set; }
        public string menutype { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string note { get; set; }
        public string path { get; set; }
        public string link { get; set; }
        public string type { get; set; }
        public sbyte published { get; set; }
        public long parent_id { get; set; }
        public long level { get; set; }
        public long component_id { get; set; }
        public int ordering { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public sbyte browserNav { get; set; }
        public long access { get; set; }
        public string img { get; set; }
        public long template_style_id { get; set; }
        public string @params { get; set; }
        public int lft { get; set; }
        public int rgt { get; set; }
        public byte home { get; set; }
        public string language { get; set; }
        public sbyte client_id { get; set; }
    }
}
