//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_user_notes
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public long catid { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public sbyte state { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public long created_user_id { get; set; }
        public System.DateTime created_time { get; set; }
        public long modified_user_id { get; set; }
        public System.DateTime modified_time { get; set; }
        public System.DateTime review_time { get; set; }
        public System.DateTime publish_up { get; set; }
        public System.DateTime publish_down { get; set; }
    }
}
