//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ampu_acymailing_listsub
    {
        public int listid { get; set; }
        public long subid { get; set; }
        public Nullable<long> subdate { get; set; }
        public Nullable<long> unsubdate { get; set; }
        public sbyte status { get; set; }
    }
}
