//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class blank
    {
        public int id { get; set; }
        public string name { get; set; }
        public string name_ua { get; set; }
        public string name_en { get; set; }
        public Nullable<int> value { get; set; }
        public string updated_at { get; set; }
    }
}
