//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_user_tokens
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string user_agent { get; set; }
        public string token { get; set; }
        public string type { get; set; }
        public long created { get; set; }
        public long expires { get; set; }
    }
}
