//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_project
    {
        public int id { get; set; }
        public short port_id { get; set; }
        public short direction_id { get; set; }
        public short dev_direction_id { get; set; }
        public string name_ru { get; set; }
        public string name_ua { get; set; }
        public string name_en { get; set; }
        public string investor_ru { get; set; }
        public string investor_ua { get; set; }
        public string investor_en { get; set; }
        public string expected_result_ru { get; set; }
        public string expected_result_ua { get; set; }
        public string expected_result_en { get; set; }
        public string dev_project_ru { get; set; }
        public string dev_project_ua { get; set; }
        public string dev_project_en { get; set; }
        public string dev_title_ru { get; set; }
        public string dev_title_ua { get; set; }
        public string dev_title_en { get; set; }
        public string tender_ru { get; set; }
        public string tender_ua { get; set; }
        public string tender_en { get; set; }
        public string contract_date_ru { get; set; }
        public string contract_date_ua { get; set; }
        public string contract_date_en { get; set; }
        public Nullable<short> fact_percent { get; set; }
        public string date_end_ru { get; set; }
        public string date_end_ua { get; set; }
        public string date_end_en { get; set; }
    }
}
