//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_content
    {
        public int id { get; set; }
        public int active { get; set; }
        public int siteid { get; set; }
        public int lan { get; set; }
        public int cat_id { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
    }
}
