//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_menu
    {
        public int id { get; set; }
        public int active { get; set; }
        public int siteid { get; set; }
        public int menu_num { get; set; }
        public int lan { get; set; }
        public int belong { get; set; }
        public int p { get; set; }
        public string title { get; set; }
        public int content_id { get; set; }
        public int category_id { get; set; }
        public string url { get; set; }
        public int sort_by { get; set; }
        public int blog_style { get; set; }
    }
}
