//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_info
    {
        public int id { get; set; }
        public int siteid { get; set; }
        public int lan { get; set; }
        public string title { get; set; }
        public int t_logo { get; set; }
        public string todey { get; set; }
        public string characteristics { get; set; }
        public string location { get; set; }
        public int corridor { get; set; }
        public string bot_info { get; set; }
        public string adres { get; set; }
        public string contacts { get; set; }
    }
}
