//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_admin_log
    {
        public int id { get; set; }
        public int siteid { get; set; }
        public System.DateTime time { get; set; }
        public string login { get; set; }
        public string action { get; set; }
    }
}
