//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_config
    {
        public int id { get; set; }
        public string url { get; set; }
        public string email { get; set; }
        public int bottom_logo { get; set; }
        public int top_img { get; set; }
        public int logo { get; set; }
    }
}
