//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_images
    {
        public int id { get; set; }
        public int siteid { get; set; }
        public int content_id { get; set; }
        public byte[] item { get; set; }
        public byte[] content { get; set; }
    }
}
