//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_admin_menu
    {
        public int id { get; set; }
        public int lan { get; set; }
        public int lan_id_for_menu { get; set; }
        public int belong { get; set; }
        public int p { get; set; }
        public string text { get; set; }
    }
}
